### ISSUE TITLE
Prettify and update styling

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc-style#1]
@pierrefortier can you help design some prettier styling for OGC (http://www.opengeospatial.org) ?

I've done some coloring, but we need something more edgy and cool. Their members include space giants like NASA and ESA. We need the document presentation to match!! 😉 

Once it's done we need to back port to https://github.com/riboseinc/metanorma-ogc

cc: @opoudjis

**Comment by ronaldtse** [comment]
You can see how it looks like now here: https://riboseinc.github.io/ogc-tcpnp/

**Comment by pierrefortier** [comment]
Hi @ronaldtse

Here are some styling updates! Let me know what you think.
[metanorma-ogc-style-mpf.zip](https://github.com/riboseinc/metanorma-ogc-style/files/2686758/metanorma-ogc-style-mpf.zip)

**Comment by opoudjis** [comment]
Btw, I was not aware of this work, which is cool, but I am tweaking the stylesheet independently (for example, I am introducing universally monospace overriding for descendants of `<tt>`. So I will need to do an even more painstaking merge of stylesheets than usual, when I use the pretty styling.

**Comment by ronaldtse** [comment]
We might as well merge it soon before the changes pile up too much.

**Comment by opoudjis** [comment]
@ronaldtse Is this still a task on me?

**Comment by ronaldtse** [comment]
@pierrefortier, we've been updating the gem and also encoded an additional document. These fully represent the features used in the OGC documents today.

Could you try to apply the changes to these new documents (already pushed to master)?

This way @opoudjis can easily integrate your new styling. Thanks!

**Comment by pierrefortier** [comment]
@ronaldtse Updated!

**Comment by ronaldtse** [comment]
@pierrefortier Thanks! This is a good start, closing this in favor of the following more specific tasks:

* https://github.com/riboseinc/metanorma-ogc-style/issues/2
* https://github.com/riboseinc/metanorma-ogc-style/issues/3
* https://github.com/riboseinc/metanorma-ogc-style/issues/4
* https://github.com/riboseinc/metanorma-ogc-style/issues/5
