### ISSUE TITLE
Style cover page metadata section

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc-style#2]
![screen shot 2019-01-19 at 7 53 00 pm](https://user-images.githubusercontent.com/11865/51426317-ee5cc100-1c23-11e9-84fb-d3169cfa1fe4.png)

The metadata needs some styling work, it needs to be flexible enough to work with responsive (maybe we should change the CSS to use flex box?

**Comment by ronaldtse** [comment]
Especially, we want the "Authors" and "Editors" to look like a separate block. Here's an example I made for CSD:

https://standards.calconnect.org/csd/cc-18003.html

The "person" and "affiliation" should be styled differently but nicely.

![screen shot 2019-01-19 at 8 05 30 pm](https://user-images.githubusercontent.com/11865/51426425-94f59180-1c25-11e9-8ae6-d608bd1eaec3.png)

**Comment by pierrefortier** [comment]
Updated!

**Comment by ronaldtse** [comment]
Not perfect but it works. Maybe we can improve this in the future. Thanks!
