### ISSUE TITLE
List styling is shifted

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc-style#3]
List bullets need to be aligned with the top content.

![screen shot 2019-01-19 at 7 52 39 pm](https://user-images.githubusercontent.com/11865/51426369-aa1df080-1c24-11e9-83e6-2ff84d4473bd.png)

**Comment by pierrefortier** [comment]
Updated!

**Comment by ronaldtse** [comment]
Thanks!
