### ISSUE TITLE
Implement styling for special text blocks

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc-style#5]
For @pierrefortier 👍 

There are three types of special text blocks.

Admonitions:

* "CAUTION", "IMPORTANT", "NOTE", "WARNING"

![screen shot 2019-01-19 at 8 00 22 pm](https://user-images.githubusercontent.com/11865/51426393-231d4800-1c25-11e9-8780-e5ab99f79ac9.png)
![screen shot 2019-01-19 at 7 52 10 pm](https://user-images.githubusercontent.com/11865/51426395-27496580-1c25-11e9-932a-c1f5b2d4c1f3.png)

Examples:

* "EXAMPLE"

![screen shot 2019-01-19 at 8 03 04 pm](https://user-images.githubusercontent.com/11865/51426403-45af6100-1c25-11e9-8e7b-e0f6930287ea.png)

Requirements:

* "Requirement", "Recommendation", "Permission"

![screen shot 2019-01-19 at 7 52 18 pm](https://user-images.githubusercontent.com/11865/51426396-2f090a00-1c25-11e9-97fd-74cdb2ef2da5.png)
![screen shot 2019-01-19 at 7 52 07 pm](https://user-images.githubusercontent.com/11865/51426397-2f090a00-1c25-11e9-8dba-34a517f0c6bf.png)

Can these all of these types have different styling, and among each type, provide suitable but different background/text colors?

Thank you!

**Comment by ronaldtse** [comment]
Ping @pierrefortier . Thanks!

**Comment by pierrefortier** [comment]
Updated!

**Comment by ronaldtse** [comment]
Looks great, thanks @pierrefortier !
