### ISSUE TITLE
Color for code blocks too light

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/metanorma-ogc-style#6]
As attached. Can we have more contrast between normal text (white background) and code blocks (light grey)?

<img width="481" alt="screen shot 2019-01-24 at 11 26 41 am" src="https://user-images.githubusercontent.com/11865/51672102-ef4a7580-1fca-11e9-910f-6c2ec7e72a15.png">

**Comment by pierrefortier** [comment]
Updated!

**Comment by opoudjis** [comment]
I've got this update, but as I'm now working on implementing it (https://github.com/riboseinc/metanorma-ogc/issues/19), you will need to notify me of any further stylesheet updates.
